name: douban
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: movie
        uses: lizheming/doumark-action@master
        with:
          id: 76509802
          type: movie
          format: csv
          dir: ./data/douban

      - name: book
        uses: lizheming/doumark-action@master
        with:
          id: 76509802
          type: book
          format: csv
          dir: ./data/douban

      - name: Commit
        uses: EndBug/add-and-commit@v8
        with:
          message: "chore: update douban data"
          add: "./data/douban"
